apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spane-opprydding
  namespace: tbd
  labels:
    team: tbd
    db_policy_user: spanebruker
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
  kafka:
    pool: nav-dev
  prometheus:
    enabled: true
    path: /metrics
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  envFrom:
    - secret: google-sql-helse-spane-helse-spane-spane-opprydding-d3d613b5
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: spane-opprydding-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: DATABASE_REGION
      value: europe-north1
    - name: DATABASE_INSTANCE
      value: helse-spane


