apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: helse-spane
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
  readiness:
    path: isready
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      cpu: 4000m
      memory: 6Gi
    requests:
      cpu: 200m
      memory: 400Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  kafka:
    pool: {{kafka-pool}}
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: false
        tier: db-f1-micro
        databases:
          - envVarPrefix: DATABASE
            name: helse-spane
            {{#if additionalDatabaseUser }}
            users:
              - name: {{ additionalDatabaseUser }}
            {{/if }}

  env:
    - name: SUBSUMSJON_TOPIC
      value: "flex.omrade-helse-etterlevelse"
