apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: helse-spane
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
  readiness:
    path: isready
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      cpu: 4000m
      memory: 6Gi
    requests:
      cpu: 200m
      memory: 400Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  kafka:
    pool: {{kafka-pool}}
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true

  env:
    - name: SUBSUMSJON_TOPIC
      value: "flex.omrade-helse-etterlevelse"
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
