name: Bygg og deploy oppryddingsapp

on:
  push:
    branches: main
    paths:
      - 'spane-opprydding/**'
      - 'workflows/opprydding-dev.yaml'
      - 'nais/opprydding/nais.yaml'

jobs:
  build:
    name: Build docker image
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.x'
          cache: 'gradle'

      - name: Build jar
        run: ./gradlew :spane-opprydding:build

      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          dockerfile: spane-opprydding/Dockerfile-opprydding
          docker_context: spane-opprydding
          image_suffix: opprydding-dev
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy:
    name: Deploy to dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/opprydding/nais.yaml,nais/opprydding/db-policy.yaml
          IMAGE: ${{ needs.set_version.outputs.image }}

