name: Bygg og deploy oppryddingsapp

on:
  push:
    branches: main
    paths:
      - 'spane-opprydding/**'
      - '.github/workflows/opprydding-dev.yaml'
      - 'nais/opprydding/nais.yaml'

jobs:
  build:
    name: Build docker image
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.x'
          cache: 'gradle'

      - name: Build jar
        run: ./gradlew :spane-opprydding:build
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          dockerfile: Dockerfile
          docker_context: spane-opprydding
          image_suffix: opprydding-dev
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy:
    name: Deploy to dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/opprydding/nais.yaml,nais/opprydding/db-policy.yaml
          IMAGE: ${{ needs.build.outputs.image }}

